function [basis] = shape_basis(element)

switch  element
    
    case{'P1'}
        
        nln=2;
        basis=struct('num',nln,...
            'n_vertex',2,...
            'fbases',{'(1-csi)/2',...
            ' (1+csi)/2'},...
            'derivative',{'-0.5',...
            ' 0.5'});
        
        
        
    case{'P2'}
        
        nln = 3;
        
        basis=struct('num',nln,...
            'n_vertex',3,...
            'fbases',{'0.5*csi.*(csi-1)',...
            '1-csi.^2',...
            '0.5*csi.*(csi+1)'},...
            'derivative',{'csi - 0.5',...
            '-2*csi',...
            'csi - 0.5'});
      
end